### ISSUE TITLE
glob2regpat is not defined on older Vims

### ISSUE THREAD

**Issue by somini** [airblade/vim-rooter#51]
I have version 7.4.52, the default on Linux Mint 17, and the plugin doesn't work anymore.

I suggest gating the new `glob2regpat` version inside
```viml
if exists('*glob2regpat')
```

**Comment by airblade** [comment]
It looks like `glob2regpat()` was added as recently as Vim 7.4.668.

I use that function to decide whether a file should be "rooted".  I don't want to reimplement [the code](https://github.com/vim/vim/blob/5d96e3ae534ade8ed09a5de9ff8fd7519537ec28/src/fileio.c#L10098-L10310) in VimScript for Vim's without the function.

The simplest fallback is just to "root" everything instead of checking the pattern.  Would you be ok with that?

**Comment by somini** [comment]
That's ok by me. You can always disable automatic rooting with 'g:rooter_manual_only'
