### ISSUE TITLE
FindRootDirectory doesn't work correctly when project folder name contains a '#'

### ISSUE THREAD

**Issue by tomatic** [airblade/vim-rooter#80]
Say I have a project folder named test-#123 and I'm in vim and the current working directory is a subfolder of the project folder. FindRootDirectory does not return the project folder in that case, whereas if the project folder name does not contain a '#', it works as expected.

**Comment by airblade** [comment]
This is an escaping problem with the `path` in `findfile({name}, {path})` and `finddir({name}, {path})`.

In 66bb4bea I started wrapping `path` with `fnameescape()` so that spaces in filenames didn't cause problems.  However `fnameescape()` also escapes `#` – e.g. `test-\#123` – and evidently `findfile()` / `finddir()` don't understand an escaped hash.

The docs for `findfile()` / `finddir()` don't talk about escaping at all.  However they do say if the path argument is omitted, they use the value of the `path` option.  And the docs for the `path` option say spaces, commas, and backslashes have to be escaped with a backslash.  So I guess those are the escaping rules we need.
