### ISSUE TITLE
symbolic link to .git causing wrong directory change

### ISSUE THREAD

**Issue by liyinsg** [airblade/vim-rooter#98]
e.g. when ~/project/.git is a symbolic link to /a/project.git,
open files under ~/project will change the root directory to /a

**Comment by airblade** [comment]
What does `:echo g:rooter_resolve_links` print?

**Comment by liyinsg** [comment]
g:rooter_resolve_links=0, the same issue after added "let g:rooter_resolve_links=1" in vimrc

**Comment by airblade** [comment]
Sorry, that was a red herring.  `g:rooter_resolve_links` applies to the file or directory you open in vim, whose root the plugin looks for, not the rooter patterns.

This occurs because vim's `finddir()` doesn't ignore symlinks.  When you open a file under `~/project`, the plugin walks up the directory tree looking for a directory containing a `.git` directory.  It finds `~/project` because that has such a directory (even though it is a symlink).

I can't see an obvious way around this at the moment.

**Comment by airblade** [comment]
I suppose the plugin could get the full path of the matched directory, then get its full path with symlinks resolved, and reject the match if they are different.

**Comment by liyinsg** [comment]
> Sorry, that was a red herring. `g:rooter_resolve_links` applies to the file or directory you open in vim, whose root the plugin looks for, not the rooter patterns.
> 
> This occurs because vim's `finddir()` doesn't ignore symlinks. When you open a file under `~/project`, the plugin [walks up the directory tree](https://github.com/airblade/vim-rooter/blob/eef98131fef264d0f4e4f95c42e0de476c78009c/plugin/rooter.vim#L88) looking for a directory containing a `.git` directory. It finds `~/project` because that has such a directory (even though it is a symlink).
> 
> I can't see an obvious way around this at the moment.

Stay inside '~/project' which contains the source code and symlink to git repo is what I wanted. In my case, it jumps to the folder which stores the real git repo.

Can we add an option doing the following things: get full path of the opened file, look up to find any directory contains .git no matter it's a symlink or directory, then change to that directory. If not found fall back to original behavior.

**Comment by airblade** [comment]
Ooops, what I said before was wrong:

> It finds ~/project because that has such a directory (even though it is a symlink).

Once vim has walked up the directory tree (using `finddir()` and found a directory containing a `.git` directory, it gets the parent of the `.git` directory and uses that as the root.

However in getting the parent of the `.git` directory it follows the symlink.  It turns out there's no way to prevent this.  See this [StackOverflow answer](https://stackoverflow.com/a/711001/151007).

So I don't think this can be fixed.
